"""add_rule_id_to_tasks

Revision ID: c95ff5b91cd4
Revises: 134300f6a381
Create Date: 2026-05-30 21:23:11.099919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95ff5b91cd4'
down_revision: Union[str, Sequence[str], None] = '134300f6a381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_rule_id', 'recurring_rules', ['rule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_rule_id', type_='foreignkey')
        batch_op.drop_column('rule_id')

    # ### end Alembic commands ###
